### PR TITLE
ingore the failed resources in wait task

### LINKED ISSUE #290: skip wait tasks for resources that fails during apply/prune
Since the apply process is changed to continue on error. We should also update the wait tasks. For any resources that are failed during apply/prune, they should be skipped in the wait tasks. Otherwise, the tasks would wait for conditions that are not going to happen.

### PR DESCRIPTION
**Pull request by Liujingfang1**
fix #290

### CODE REVIEW

**Review by mortent — APPROVED** [review]
Looks good to me. I'll let @seans3 take a look too.

**Comment by seans3** [comment]
/hold

...regression in ResourceGroup pruning. We'll need to fix that first.

**Comment by Liujingfang1** [comment]
@seans3 Is the regression from this PR?

**Comment by seans3** [comment]
> Sean Sullivan Is the regression from this PR?

This PR broke pruning: https://github.com/kubernetes-sigs/cli-utils/pull/291

Let's not change anything until the pruning is fixed.

**Review by seans3 — APPROVED** [review]
/lgtm

**Pull request merged**
