### PR TITLE
chore: Add example test summary

### PR DESCRIPTION
**Pull request by karlkfi**
example output:

```
TEST                   RESULT
crds.md                Succeeded
helloapp.md            Succeeded
init.md                Succeeded
inventoryNamespace.md  Succeeded
MultipleServices.md    Succeeded
pruneAndDelete.md      Succeeded
pruneBasic.md          Succeeded
pruneNamespace.md      Succeeded
serverSideApply.md     Succeeded

Example Tests Succeeded
```

### CODE REVIEW

**Comment by karlkfi** [comment]
Ugh. the test container doesn't have `column` installed...

**Comment by karlkfi** [comment]
Installing column (and all of bsdextrautils) seems like it might not be easy to get approved in the `kubekins-e2e` image we're running tests in. So I added an apt-get line to install it in the prow-specific make command.

**Comment by karlkfi** [comment]
Example test output is finally readable without expanding the whole log:
example-test-summary

**Review by mortent — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
