### PR TITLE
More checks in E2E tests

### PR DESCRIPTION
**Pull request by mortent**
Our current E2E tests checks for output, but mostly doesn't check whether we get the expected result in the cluster. This PR adds more checks to make sure that the resulting state in the cluster is also as expected.

Ref: https://github.com/kubernetes-sigs/cli-utils/pull/157

@phanimarupaka @monopole @seans3

### CODE REVIEW

**Comment by mortent** [comment]
This currently fails as expected. Should pass after #157 is merged.

**Comment by phanimarupaka** [comment]
Looks good. You might want to add such kubectl validations for MultipleServices.md as well.
1. Check if other grouping resources are untouched if one grouping is destroyed.
2. Applying one grouping should not have any effects on other grouping.

**Comment by mortent** [comment]
@phanimarupaka I intend to do another PR to update the MultipleServices.md tests.

**Pull request merged**
