### PR TITLE
Add a new flag value `force-adopt` to the `--inventory-policy` flag

### PR DESCRIPTION
**Pull request by haiyanmeng**
`force-adopt` allows the current inventory take ownership of any objects.

### CODE REVIEW

**Comment by Liujingfang1** [comment]
What is the motivation to expose the AdoptAll policy to the cli. I thought we only expect the library consumer to use AdoptAll.

**Comment by haiyanmeng** [comment]
> What is the motivation to expose the AdoptAll policy to the cli. I thought we only expect the library consumer to use AdoptAll.

Quick testing.

**Review by seans3 — APPROVED** [review]
This looks good. I'll let others chime in, then we can merge.

**Review by seans3 — APPROVED** [review]
/lgtm

**Pull request merged**
