### PR TITLE
Use rand from apimachinery to avoid seeding rng every time

### PR DESCRIPTION
**Pull request by ash2k**
https://github.com/kubernetes/apimachinery/blob/master/pkg/util/rand/rand.go

### CODE REVIEW

**Comment by ash2k** [comment]
I'm now part of this org too, let's see if this works

/ok-to-test

**Comment by ash2k** [comment]
Friendly ping @mortent

**Comment by ash2k** [comment]
/assign seans3

@seans3 Could you have a look? I'd like to make more (and more interesting) improvements to the library as I'd like to start using it.

**Review by mortent — APPROVED** [review]
Looks good to me. Thanks for contributing.
/lgtm
/approve

**Pull request merged**
