### PR TITLE
Adds e2e test for basic pruning functionality

### PR DESCRIPTION
**Pull request by seans3**
* Adds end-to-end test for basic pruning functionality

### CODE REVIEW

**Comment by mortent** [comment]
So looks good, but can we add some more checks? Currently we are only verifying that we see the desired print statements, but we should also check that the state in the cluster is what we expect. We have had these kinds of bugs in the past.

**Comment by seans3** [comment]
> So looks good, but can we add some more checks? Currently we are only verifying that we see the desired print statements, but we should also check that the state in the cluster is what we expect. We have had these kinds of bugs in the past.

Good Point. Added tests for resources in the cluster. Have a look.

**Comment by mortent** [comment]
Looks good to me. Can we squash the commits?

**Comment by seans3** [comment]
> Looks good to me. Can we squash the commits?

Squashed.

**Pull request merged**
