### PR TITLE
split inventory and resources in the apply interface

### PR DESCRIPTION
**Pull request by Liujingfang1**
Change the `Applier.Run` from
```
func (a *Applier) Run(ctx context.Context, objects []*unstructured.Unstructured,
options Options) <-chan event.Event {}
```
to 
```
func (a *Applier) Run(ctx context.Context, inventory *unstructured.Unstructured, objects []*unstructured.Unstructured,
options Options) <-chan event.Event {
```

### CODE REVIEW

**Comment by mortent** [comment]
This makes sense. Long term I don't think we want the type of the inventory object to be `*unstructured.Unstructured`, but rather just the information needed to create/lookup the object containing the inventory. The details of how it is created and updated should be part of the Provider.

**Comment by Liujingfang1** [comment]
This is an intermediate state. I plan to change it to `inventory.Inventory`.

**Comment by mortent** [comment]
Sounds good. This looks good to me. I'll let @seans3 take a look too.

**Comment by Liujingfang1** [comment]
The e2e test failed, I'm working on it.

**Comment by Liujingfang1** [comment]
The tests all passed. Please take a look @seans3

**Comment by seans3** [comment]
This looks good. I'm going to submit the migrate PR first if that is OK.

**Comment by Liujingfang1** [comment]
Yes, that's OK.

**Comment by Liujingfang1** [comment]
Rebased on recent change. PTAL @seans3

**Review by seans3 — APPROVED** [review]
/lgtm

**Pull request merged**
