### PR TITLE
Don't store Context inside a struct, pass it explicitly to each function that needs it.

### PR DESCRIPTION
**Pull request by rohitagarwal003**
This is from the context package documentation: https://pkg.go.dev/context

Tested by running `go test ./...` inside `pkg/kstatus`.

### CODE REVIEW

**Review by ash2k — APPROVED** [review]
/ok-to-test
/lgtm

**Review by mortent — APPROVED** [review]
/approve

**Comment by mortent** [comment]
test failure is due to https://github.com/kubernetes-sigs/cli-utils/issues/534
/test cli-utils-presubmit-master

**Pull request merged**
