### PR TITLE
Update k8s.io dependencies to v0.27.2

### PR DESCRIPTION
**Pull request by ash2k**
Based on and contains commits from https://github.com/kubernetes-sigs/cli-utils/pull/619.

### CODE REVIEW

**Comment by ash2k** [comment]
We actually cannot update to the v0.27.3 or v0.27.4 without stepping into the mess of https://github.com/kubernetes/kubernetes/issues/118340. We'll have to go directly to v0.28.x.

**Comment by ash2k** [comment]
@seans3 @mortent This passes CI, finally.

**Review by seans3 — APPROVED** [review]
/lgtm
/approve

Thanks for the clean-up

**Comment by seans3** [comment]
Also addresses: https://github.com/kubernetes/kubernetes/issues/119840

**Pull request merged**
