### PR TITLE
Enable parallel apply

### PR DESCRIPTION
**Pull request by rquitales**
To enable parallel apply, we can loop our apply logic in separate Go threads instead of a synchronous loop.

### CODE REVIEW

**Comment by rquitales** [comment]
CLA signed.

**Comment by rquitales** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Signed.

**Comment by rquitales** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

/check-cla

**Comment by karlkfi** [comment]
Looks like a good start. Nice to see it passes tests.

I think we're gonna want to be able to limit the number of concurrent applies tho. There's a couple options discussed here: https://www.tegh.net/2020/04/29/semaphored-wait-group/

Then we're want to pipe that through the ApplyOptions with something like MaxConcurrentRequests.

And then we're gonna need a way to cancel the whole group, or at least cause each goroutine to cancel. I think we can do this by passing through the Context, which we've been meaning to do for a while. That can be done by adding the Context to the TaskContext. Then at the beginning of each go routine, we can check if the context is done to exit early. That way the WaitGroup will drain nicely when cancelled, effectively skipping unstarted goroutines.

Perhaps you can attempt the TaskContext.Context refactor first in a separate PR?

**Pull request closed without merging**
