### PR TITLE
Kubernetes 1.31.1 libraries

### PR DESCRIPTION
**Pull request by ash2k**

### CODE REVIEW

**Comment by ash2k** [comment]
PTAL @karlkfi @seans3

**Review by seans3 — COMMENTED** [review]
This looks good to me. I'll wait on Karl for a bit to ensure he's OK with it.

/lgtm

**Comment by ash2k** [comment]
This is blocking me from updating some other dependencies in my project. Could someone merge this please?

**Comment by ash2k** [comment]
Thank you, @seans3!

**Pull request merged**
