### PR TITLE
Add json printer

### PR DESCRIPTION
**Pull request by chunglu-chou**
This change is to make the status command work for other inventory types.
Add json printer to support json output format including a new field named inventory-name.
Add testing data for json output format.

### CODE REVIEW

**Comment by mortent** [comment]
Code looks good. Could we add a test for this functionality?

**Comment by chunglu-chou** [comment]
@mortent Yes, I think I could reuse the test cases in the current one and just make it output as json format to verify the result.

**Review by mortent — APPROVED** [review]
/lgtm

**Pull request merged**
