### PR TITLE
Create go.yml

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by monopole** [comment]
prow insufficient?

**Comment by pwittrock** [comment]
Was talking with Sean about this.  GH checks well integrated into the platform and IMHO will be easier for folks to edit.  One nice thing is that the configuration is in the repo, so we don't have to make changes to the prow repo to configure them.

**Comment by monopole** [comment]
prow runs `make prow-presubmit-check`.

our config is already in repo and runnable from the command line.

**Comment by mortent** [comment]
I'm open to trying to GH, but prow is convenient since it supports commands for re-running tests. It also integrates well with tide (for automatic merge) and it allows multiple checks so we could potentially add a new target for e2e tests. The last two might work well for GH too, but I have never tried it.

**Comment by monopole** [comment]
cli-utils now slots into the same dashboard as the rest of k8s.
https://prow.k8s.io/?repo=kubernetes-sigs%2Fcli-utils

also, it's pretty sane to be able run exactly the CI presubmit test from the command line.

**Pull request closed without merging**
