### PR TITLE
Upgrade k8s dependencies

### PR DESCRIPTION
**Pull request by etefera**
Updating dependencies and test to match https://github.com/GoogleContainerTools/kpt/pull/1540

### CODE REVIEW

**Comment by Liujingfang1** [comment]
/ok-to-test

@seans3

**Review by seans3 — APPROVED** [review]
Let's squash the three commits, then I'll add LGTM.

This looks good. It updates `kubectl` code from `v0.18.10` to `v0.20.4`, which is the latest. Let's keep our eye open for any problems.

**Pull request merged**
