### PR TITLE
fix: Allow empty set of apply objects

### PR DESCRIPTION
**Pull request by karlkfi**
- Add e2e test to ensure the inventory is still correctly created
  and destroyed when the apply object set is empty.

Fixes https://github.com/GoogleContainerTools/kpt/issues/2857

### CODE REVIEW

**Comment by Liujingfang1** [comment]
> and destroyed when the apply object set is empty.

Is this destroy operation only for destroyer being called explicitly?
In other words, the inventory object is not destroyed even the object set is empty after after a replace?

**Comment by karlkfi** [comment]
> > and destroyed when the apply object set is empty.
> 
> Is this destroy operation only for destroyer being called explicitly? In other words, the inventory object is not destroyed even the object set is empty after after a replace?

The Applier never deletes the inventory. Only the Destroyer deletes the inventory.

The new test (like most of the others) calls the applier, validates the result, and then calls the destroyer, and validates the result.

The only behavioral change here is that the InvAddtask now (again) executes on every Applier run.

**Pull request merged**
